### PR TITLE
 Rename to .js and cleanup formatting

### PR DESCRIPTION
**Pull request by gregorwolf**

### CODE REVIEW

**Comment by StregaTechnologies** [comment]
Sorry, not accepting changes to this code as this is not the actual source.

**Comment by gregorwolf** [comment]
But please publish at least code with the correct file name extensions and cleanup the formatting in your source.

**Comment by StregaTechnologies** [comment]
Thanks Gregor, but this is not a javascript file.  The contents of the file are used within TTN, you cannot upload JS files to TTN.  As explained, this is not the source for the code.  Your comments will be passed on to the development team.

**Comment by gregorwolf** [comment]
Based on what I've found in the [TTN Forums the language is JavaScript / ECMAScript](https://www.thethingsnetwork.org/forum/t/is-there-any-documentation-on-payload-functions/3441/3). So .js would be the correct filename extenstion.

**Comment by StregaTechnologies** [comment]
Thank you for your comments Gregor.

**Pull request closed without merging**
